name: pokemon_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.5.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.1
  get_it: ^7.6.0
  http: ^0.13.6
  injectable: ^2.1.2
  intl: ^0.18.1
  mockito: ^5.4.2
  path_provider: ^2.0.15
  responsive_framework: ^0.2.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/pokemon_logo.png
  android_12:
    color: "#ffffff"
    image: assets/images/pokemon_logo.png
